services:
  pai:
    build:
      context: .
      dockerfile: DockerFile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
