# Use an official base image with Python 3.10 support
FROM ubuntu:22.04

# Set the working directory
WORKDIR /pai

# Install system dependencies
RUN apt update && apt upgrade -y && \
    apt install -y \
        software-properties-common \
        curl \
        git \
        build-essential \
        python3.10 \
        python3.10-distutils \
        python-is-python3 \
        python3-pip \
        net-tools \
        npm \
        libsndfile1 \
        libasound2-dev \
        ffmpeg \
        autotools-dev \
        automake \
        libtool && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    curl https://bootstrap.pypa.io/get-pip.py | python3.10 && \
    apt-get clean

# Install Rust using rustup
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Add Rust to PATH
ENV PATH="/root/.cargo/bin:$PATH"

# Clone and build eSpeak-NG
RUN git clone https://github.com/espeak-ng/espeak-ng.git /pai/espeak-ng
WORKDIR /pai/espeak-ng
RUN ./autogen.sh && ./configure --without-pulseaudio && make && make install

# Install Node dependencies
WORKDIR /pai/web
COPY web/package.json web/package-lock.json ./
RUN npm install

# Install Python dependencies
WORKDIR /pai/api
COPY api/requirements.txt ./
RUN python3 -m pip install --upgrade pip setuptools wheel
RUN pip3 install -r requirements.txt

# Install TTS and other tools (CPU only, no CUDA)
RUN pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir
RUN pip install --ignore-installed --no-cache-dir -U blinker
RUN pip install TTS
RUN pip install simpleaudio gtts fastapi==0.112.0

# Set default environment variable
ENV OPENAI_API_KEY=${OPENAI_API_KEY:-"DUMMY-KEY"}

# Copy the rest of the project
COPY . /pai

# Expose port 4000 for the web service
EXPOSE 4000

# Default command to start the web application
CMD ["npm", "start", "--prefix", "/pai/web"]
